/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    // TODO can this be replaced using the version catalog?
    val quarkusPluginId: String by settings
    val quarkusPluginVersion: String by settings

    val foojayResolverPlugin: String by settings
    val foojayResolverPluginVersion: String by settings

    plugins {
        id(quarkusPluginId) version quarkusPluginVersion
        // Apply the foojay-resolver plugin to allow automatic download of JDKs
        id(foojayResolverPlugin) version foojayResolverPluginVersion
    }
}

rootProject.name = "cold-frontier"
include("backend", "frontend", "lib")
